set nocompatible 
source ~/dotfiles/vim/bundles/pathogen/autoload/pathogen.vim
"Pathogen calls
call pathogen#infect('~/dotfiles/vim/bundles')
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

"temp
" Quickly edit/reload the vimrc file
let mapleader=","
nmap <silent> <leader>ev :e $MYVIMRC<CR>
nmap <silent> <leader>sv :so $MYVIMRC<CR>

"coloring
syntax on
"let g:solarized_termcolors=256
"set background=dark
set background=light
colorscheme solarized
"colorscheme mustang
"This is for Arduino files
au BufNewFile,BufRead *.ino set filetype=cpp

set tabstop=4
set shiftwidth=4
set autoindent
set smartindent
set nowrap
set number
"show matching paren
set showmatch 
set hlsearch
nmap <silent> <leader>/ :nohlsearch<CR> 
set incsearch
set nobackup
set noswapfile
cmap w!! w !sudo tee % >/dev/null "sudo after file is loaded
filetype plugin on
"allow hiding of buffers"
set hidden 

if has("autocmd")
" When editing a file, always jump to the last cursor position
   autocmd BufReadPost *
     \ if line("'\"") > 0 && line ("'\"") <= line("$") |
	 \   exe "normal g'\"" |
	 \ endif
	autocmd BufReadPost * :DetectIndent 
endif



"key mappings
map <leader>m :MRU<CR>
map <tab> <C-w>
map <leader>n :NERDTree<CR>
map :cam<CR> :s/_\([a-z]\)/\U\1/g<CR>
map <leader>l :TlistToggle<CR>
map <leader>d :r!date "+\%A \%Y-\%m-\%d"<CR>
map <C-Up> :Up<CR>
map <C-Down> :Dn<CR>
imap <D-Space> <C-n> 
map <C-h> :bp<CR>
map <C-l> :bn<CR>
map <F5> :DbgStepInto<cr>
map <F6> :DbgStepOver<cr>
map <F7> :DbgStepOut<cr>
map <F8> :DbgRun<cr>
map <F9> :DbgDetach<cr>
map :Bp<cr>  :DbgToggleBreakpoint<cr>
" command GREP :execute 'vimgrep /'.expand('<cword>').'/gj **/*' | copen


let Tlist_WinWidth = 50
let Tlist_Show_One_File = 1

"detect indent prefer tabs
let g:detectindent_preferred_noexpandtab = 1
let g:detectindent_preferred_indent = 4
autocmd Filetype ruby let g:detectindent_preferred_expandtab = 1
autocmd Filetype ruby let g:detectindent_preferred_indent = 2


let g:Powerline_symbols = 'fancy'

set statusline=%p%%\ %f%y\ %(\[%R]%)%=\ %(\[%M%R%H]%)%=\ %4l,%02c%2V\ %P%*
set laststatus=2



