#!/usr/bin/env sh

# bar settings
yabai -m config status_bar                   on
yabai -m config status_bar_text_font         "FuraCode Nerd Font:Retina:16.0"
yabai -m config status_bar_icon_font         "FuraCode Nerd Font:Retina:18.0"
yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  I II III IV V VI VII VIII IX X
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config window_border                off
yabai -m config window_border_width          4
#
yabai -m config active_window_border_color   0xffd58946
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   5

center_grid='26:26:5:5:16:16'
#yabai -m query --windows to query windows
#https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc
yabai -m rule --add app="Simulator" manage=off border=off 
yabai -m rule --add app="Cisco AnyConnect Secure Mobility Client" manage=off border=off

yabai -m rule --add app=Dash manage=off sticky=on grid="26:26:3:3:20:20"
yabai -m rule --add app="A Companion for SwiftUI" border=off manage=off
yabai -m rule --add app=Xcode title="^$" manage=off border=off
yabai -m rule --add app="Microsoft Outlook" title="^.*Reminder.*$" manage=off border=off
#yabai -m rule --add app="Microsoft Outlook" manage=off border=off


yabai -m rule --add app='Messages' manage=off sticky=on grid="$center_grid"
yabai -m rule --add app='Things' manage=off grid="$center_grid"
yabai -m rule --add app='Spotify' manage=off sticky=on grid="$center_grid"
yabai -m rule --add app='iTerm2' title="^.*Hotkey Window$" manage=off
yabai -m rule --add app='Alfred' manage=off
yabai -m rule --add app='kitty' manage=off
yabai -m rule --add app='Alacritty' manage=off
yabai -m rule --add app='System Preferences' manage=off sticky=on grid="$center_grid"

echo "yabai configuration loaded.."
