ZSH="${HOME}/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh"
plugins=(git common-aliases pod vi-mode)
COMPLETION_WAITING_DOTS="true"
export KEYTIMEOUT=1
ZSH_THEME=""
source <(antibody init)
antibody bundle < $HOME/dotfiles/zsh/zsh_plugins.txt

export PATH=/opt/local/bin:/opt/local/sbin:~/.rbenv/bin:~/.local/bin:~/dotfiles/scripts:/usr/local/bin:/usr/local/opt/ruby/bin:$(brew --prefix coreutils)/libexec/gnubin:/usr/local/bin:$PATH
if [[ ! -z "$NVIM_LISTEN_ADDRESS" ]];
then 
  alias vim='nvr -s --remote-silent'
else
  alias vim=nvim
fi
alias vi=vim
alias pi='be pod install'
alias gsh='git stash'
alias gshki='git stash --keep-index'
alias gshp='git stash pop'
alias gshs='git stash show -p'
alias gs='git status'
alias pd='pushd'
alias po='popd'
alias be='bundle exec'
alias d='docker'
alias dc='docker-compose'
alias dm='docker-machine'
alias dcon='docker container'
alias dim='docker image'
alias hg='history 0 | grep '
alias js='python -m json.tool'
unalias gsi
function dm-env() {
  eval "$(docker-machine env "${1:-default}")"
}

export PURE_GIT_UNTRACKED_DIRTY=0
export HISTFILESIZE=30000
export EDITOR=nvim
set -o vi
bindkey -M viins '^k' vi-cmd-mode
# ZLE hooks for prompt's vi mode status
function zle-line-init zle-keymap-select {
	# Change the cursor style depending on keymap mode.
	case $KEYMAP {
		vicmd)
			printf '\e[0 q' # Box.
			;;

		viins|main)
			printf '\e[6 q' # Vertical bar.
			;;
	}
}
zle -N zle-line-init
zle -N zle-keymap-select
DDATA=~/Library/Developer/Xcode/DerivedData
#export SOURCEKIT_LOGGING=3
export SOURCEKIT_TOOLCHAIN_PATH=/Library/Developer/Toolchains/swift-latest.xctoolchain
#export NVIM_PYTHON_LOG_LEVEL=DEBUG
#export NVIM_PYTHON_LOG_FILE=~/dotfiles/nvim/nvim/plugins.log
eval "$(rbenv init -)"
export FASTLANE_USER=tylerc230@gmail.com
export FASTLANE_SKIP_UPDATE_CHECK=1
export PILOT_USERNAME=tylerc230@gmail.com                          
unalias history

# This function calls the script below when loaded by
# the shell inside of neovim. It must be placed somewhere in
# your default shell's rc file e.g. ~/.zshrc

neovim_autocd() {
    [[ $NVIM_LISTEN_ADDRESS ]] && ~/dotfiles/scripts/neovim_autocd.py
}
chpwd_functions+=( neovim_autocd )
alias ry="brew services restart koekeishiya/formulae/yabai"
