# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git brew heroku osx rails rake rvm svn vi-mode)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH=/Users/tcasselman/.rvm/gems/ruby-1.9.2-p136/bin:/Users/tcasselman/.rvm/gems/ruby-1.9.2-p136@global/bin:/Users/tcasselman/.rvm/rubies/ruby-1.9.2-p136/bin:/Users/tcasselman/.rvm/bin:/Users/tcasselman/Software/cityville_mobile/scripts:/usr/local/sbin:/usr/local/bin:/Users/tcasselman/dotfiles/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin:/usr/X11/bin:/Developer/usr/bin/:/usr/local/mysql/bin
#from bash
export EDITOR=vim
set -o vi
alias pd='pushd'
alias po='popd'

PATH=/Users/tcasselman/Software/cityville_mobile/scripts:/usr/local/sbin:/usr/local/bin:~/dotfiles/bin:$PATH:/Developer/usr/bin/:/usr/local/mysql/bin

VIMRUNTIME=~/.vim
export HISTFILESIZE=3000
export TERM=xterm-color
export CLICOLOR=1

export TERM="xterm-256color"
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

#work
export SVNURL=https://svn.zynga.com/svn/cityville-mobile/project/
export SVNURL2=https://svn.zynga.com/svn/forestville/project/
DEPLOYSRV=iphone-dev-01.ec2.zynga.com

export DEV=citymobile-dev-01.ec2.zynga.com
export DEV2=forestmobile-dev-01.ec2.zynga.com
export DONE=~/Dropbox/docs/done.txt
SVNSRV=https://svn.zynga.com/svn/cityville-mobile/server/
alias localize='php Server/game/scripts/compile_locale_xml.php'
STAGE=184.72.207.65
