ZSH="${HOME}/Library/Caches/antibody/https-COLON--SLASH--SLASH-github.com-SLASH-robbyrussell-SLASH-oh-my-zsh"
plugins=(git docker common-aliases pod pip python vi-mode web-search)
COMPLETION_WAITING_DOTS="true"
source <(antibody init)
antibody bundle < $HOME/dotfiles/zsh/zsh_plugins.txt

export PATH=/opt/local/bin:/opt/local/sbin:~/.rbenv/bin:~/.local/bin:~/dotfiles/scripts:/usr/local/bin:$(brew --prefix coreutils)/libexec/gnubin:/usr/local/bin:$PATH
if [[ ! -z "$NVIM_LISTEN_ADDRESS" ]];
then 
  alias vim='nvr -s --remote-silent'
else
  alias vim=nvim
fi
alias vi=vim
alias pi='pod install'
alias gsi='nvr -s --remote-tab-silent -cGstatus fake.txt'
alias gsh='git stash'
alias gshp='git stash pop'
alias gs='git status'
alias pd='pushd'
alias po='popd'
alias pi='pod install'
alias be='bundle exec'
alias d='docker'

export PURE_GIT_UNTRACKED_DIRTY=0
export HISTFILESIZE=3000
export EDITOR=vim
set -o vi
bindkey -M viins '^s' vi-cmd-mode
DDATA=~/Library/Developer/Xcode/DerivedData
export SOURCEKIT_LOGGING=4
eval "$(rbenv init -)"
